CREATE TABLE tx_measure_domain_model_measure (
	title varchar(255) NOT NULL DEFAULT '',
	art int(11) DEFAULT '0' NOT NULL,
	shortdescription text NOT NULL DEFAULT '',
	aims text NOT NULL DEFAULT '',
	aimgroup text NOT NULL DEFAULT '',
	occupationalarea text NOT NULL DEFAULT '',
	agestart int(11) NOT NULL DEFAULT '0',
	ageend int(11) NOT NULL DEFAULT '0',
	gender int(11) NOT NULL DEFAULT '0',
	migration int(11) NOT NULL DEFAULT '0',
	rights int(11) NOT NULL DEFAULT '0',
	school int(11) NOT NULL DEFAULT '0',
	graduate int(11) NOT NULL DEFAULT '0',
	ineducation int(11) NOT NULL DEFAULT '0',
	duration int(11) NOT NULL DEFAULT '0',
	startoffer date DEFAULT NULL,
	registration date DEFAULT NULL,
	finance text NOT NULL DEFAULT '',
	name varchar(255) NOT NULL DEFAULT '',
	address varchar(255) NOT NULL DEFAULT '',
	zip varchar(255) NOT NULL DEFAULT '',
	city varchar(255) NOT NULL DEFAULT '',
	person1 varchar(255) NOT NULL DEFAULT '',
	phone1 varchar(255) NOT NULL DEFAULT '',
	email1 varchar(255) NOT NULL DEFAULT '',
	person2 varchar(255) NOT NULL DEFAULT '',
	phone2 varchar(255) NOT NULL DEFAULT '',
	email2 varchar(255) NOT NULL DEFAULT '',
	www1 varchar(255) NOT NULL DEFAULT '',
	www2 varchar(255) NOT NULL DEFAULT '',
	file int(11) unsigned NOT NULL DEFAULT '0',
	info text NOT NULL DEFAULT '',
	carrier int(11) unsigned NOT NULL DEFAULT '0',
);

CREATE TABLE tx_measure_domain_model_carrier (
	title varchar(255) NOT NULL DEFAULT '',
	address varchar(255) NOT NULL DEFAULT '',
	zip varchar(255) NOT NULL DEFAULT '',
	city varchar(255) NOT NULL DEFAULT '',
	phone varchar(255) NOT NULL DEFAULT '',
	www varchar(255) NOT NULL DEFAULT '',
	email1 varchar(255) NOT NULL DEFAULT '',
	email2 varchar(255) NOT NULL DEFAULT '',
	email3 varchar(255) NOT NULL DEFAULT '',
	email4 varchar(255) NOT NULL DEFAULT '',
	email5 varchar(255) NOT NULL DEFAULT '',
	description text NOT NULL DEFAULT '',
);

CREATE TABLE tx_measure_measure_carrier_mm (
	uid_local int(11) DEFAULT '0' NOT NULL,
	uid_foreign int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	sorting_foreign int(11) DEFAULT '0' NOT NULL,
	KEY uid_local (uid_local),
	KEY uid_foreign (uid_foreign)
);
